music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(523, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(494, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(330, music.beat(BeatFraction.Double))
basic.pause(200)
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(523, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(494, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(415, music.beat(BeatFraction.Double))
basic.pause(850)
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(784, music.beat(BeatFraction.Half))
music.playTone(698, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(698, music.beat(BeatFraction.Half))
music.playTone(659, music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Double))
basic.pause(200)
music.playTone(494, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(415, music.beat(BeatFraction.Double))
basic.pause(200)
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(370, music.beat(BeatFraction.Whole))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(523, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(494, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(330, music.beat(BeatFraction.Double))
basic.pause(200)
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(523, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(494, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(415, music.beat(BeatFraction.Double))
basic.pause(850)
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(784, music.beat(BeatFraction.Half))
music.playTone(698, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(698, music.beat(BeatFraction.Half))
music.playTone(659, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Double))
basic.pause(1000)
